import time
import Proyecto.Grafo as gr
import random

print('Creacion de grafos', time.strftime("%H:%M:%S"))

"""grafo=gr.Grafo()
grafo.GrafoMalla(5,5)
grafo.ArchivoGrafo('grafoMalla25')
Kruskal=grafo.Kruskal()
Kruskal.ArchivoGrafo('Kruskal25Malla')
KruskalInver=grafo.KruskalInverso()
KruskalInver.ArchivoGrafo('KruskalInverMalla')
arbolprim=grafo.Prim()
arbolprim.ArchivoGrafo('ArbolPrimMalla')
grafo2=gr.Grafo()
grafo2.GrafoMalla(10,10) 
grafo2.ArchivoGrafo('grafoMalla100')
Kruskal2=grafo2.Kruskal()
Kruskal2.ArchivoGrafo('Kruskal100Malla')
KruskalInver2=grafo2.KruskalInverso()
KruskalInver2.ArchivoGrafo('KruskalInver100Malla')
arbolprim2=grafo2.Prim()
arbolprim2.ArchivoGrafo('ArbolPrim100Malla')

grafo3=gr.Grafo()
grafo3.GrafoSimple(100, 50)
grafo3.ArchivoGrafo('grafoSimple100')
Kruskal3=grafo3.Kruskal()
Kruskal3.ArchivoGrafo('Kruskal100Simple')
KruskalInver3=grafo3.KruskalInverso()
KruskalInver3.ArchivoGrafo('KruskalInver100Simple')
arbolprim3=grafo3.Prim()
arbolprim3.ArchivoGrafo('ArbolPrim100Simple')
grafo4=gr.Grafo()
grafo4.GrafoSimple(1000, 50)
grafo4.ArchivoGrafo('grafoSimple1000')
Kruskal4=grafo4.Kruskal()
Kruskal4.ArchivoGrafo('Kruskal1000Simple')
KruskalInver4=grafo4.KruskalInverso()
KruskalInver4.ArchivoGrafo('KruskalInver1000Simple')
arbolprim4=grafo4.Prim()
arbolprim4.ArchivoGrafo('ArbolPrim1000Simple')"""

"""grafo5=gr.Grafo()
grafo5.GrafoGilbert(100, 0.1)
grafo5.ArchivoGrafo('grafoGilbert100')
Kruskal5=grafo5.Kruskal()
Kruskal5.ArchivoGrafo('Kruskal100Gilbert')
KruskalInver5=grafo5.KruskalInverso()
KruskalInver5.ArchivoGrafo('KruskalInver100Gilbert')
arbolprim5=grafo5.Prim()
arbolprim5.ArchivoGrafo('ArbolPrim100Gilbert')"""
grafo6=gr.Grafo()
grafo6.GrafoGilbert(1000, 0.01)
grafo6.ArchivoGrafo('grafoGilbert1000')
Kruskal6=grafo6.Kruskal()
Kruskal6.ArchivoGrafo('Kruskal1000Gilbert')
KruskalInver6=grafo6.KruskalInverso()
KruskalInver6.ArchivoGrafo('KruskalInver1000Gilbert')
arbolprim6=grafo6.Prim()
arbolprim6.ArchivoGrafo('ArbolPrim1000Gilbert')
"""
grafo7=gr.Grafo()
grafo7.GrafoErdosReny(100, 120)
grafo7.ArchivoGrafo('grafoErdosReny100')
Kruskal7=grafo7.Kruskal()
Kruskal7.ArchivoGrafo('Kruskal100ErdosReny')
KruskalInver7=grafo7.KruskalInverso()
KruskalInver7.ArchivoGrafo('KruskalInver100ErdosReny')
arbolprim7=grafo7.Prim()
arbolprim7.ArchivoGrafo('ArbolPrim100ErdosReny')
grafo8=gr.Grafo()
grafo8.GrafoErdosReny(1000, 1200)
grafo8.ArchivoGrafo('grafoErdosReny1000')
Kruskal8=grafo8.Kruskal()
Kruskal8.ArchivoGrafo('Kruskal1000ErdosReny')
KruskalInver8=grafo8.KruskalInverso()
KruskalInver8.ArchivoGrafo('KruskalInver1000ErdosReny')
arbolprim8=grafo8.Prim()
arbolprim8.ArchivoGrafo('ArbolPrim1000ErdosReny')

grafo9=gr.Grafo()
grafo9.GrafoDorogovtsevMendes(100)
grafo9.ArchivoGrafo('grafoDorogovtsevMendes100')
Kruskal9=grafo9.Kruskal()
Kruskal9.ArchivoGrafo('Kruskal100DorogovtsevMendes')
KruskalInver9=grafo9.KruskalInverso()
KruskalInver9.ArchivoGrafo('KruskalInver100DorogovtsevMendes')
arbolprim9=grafo9.Prim()
arbolprim9.ArchivoGrafo('ArbolPrim100DorogovtsevMendes')
grafo10=gr.Grafo()
grafo10.GrafoDorogovtsevMendes(1000)
grafo10.ArchivoGrafo('grafoDorogovtsevMendes1000')
Kruskal10=grafo10.Kruskal()
Kruskal10.ArchivoGrafo('Kruskal1000DorogovtsevMendes')
KruskalInver10=grafo10.KruskalInverso()
KruskalInver10.ArchivoGrafo('KruskalInver1000DorogovtsevMendes')
arbolprim10=grafo10.Prim()
arbolprim10.ArchivoGrafo('ArbolPrim1000DorogovtsevMendes')

grafo11=gr.Grafo()
grafo11.GrafoBarabasiAlbert(100, 5)
grafo11.ArchivoGrafo('grafoBarabasiAlbert100')
Kruskal11=grafo11.Kruskal()
Kruskal11.ArchivoGrafo('Kruskal100BarabasiAlbert')
KruskalInver11=grafo11.KruskalInverso()
KruskalInver11.ArchivoGrafo('KruskalInver100BarabasiAlbert')
arbolprim11=grafo11.Prim()
arbolprim11.ArchivoGrafo('ArbolPrim100BarabasiAlbert')
grafo12=gr.Grafo()
grafo12.GrafoBarabasiAlbert(1000, 5)
grafo12.ArchivoGrafo('grafoBarabasiAlbert1000')
Kruskal12=grafo12.Kruskal()
Kruskal12.ArchivoGrafo('Kruskal1000BarabasiAlbert')
KruskalInver12=grafo12.KruskalInverso()
KruskalInver12.ArchivoGrafo('KruskalInver1000BarabasiAlbert')
arbolprim12=grafo12.Prim()
arbolprim12.ArchivoGrafo('ArbolPrim1000BarabasiAlbert')
"""
print('termino de crear grafos ', time.strftime("%H:%M:%S"))