import time
import Proyecto.Grafo as gr
import random

print('Creacion de grafos', time.strftime("%H:%M:%S"))

grafo=gr.Grafo()
grafo.GrafoMalla(5,5)
grafo.ArchivoGrafo('grafoMalla25')
nodo=random.choice(grafo.ObtenerNodos())
kstra,distancia=grafo.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('MallaDijkstra25',distancia)

grafo2=gr.Grafo()
grafo2.GrafoMalla(10,10)
grafo2.ArchivoGrafo('grafoMalla100')
nodo=random.choice(grafo2.ObtenerNodos())
kstra,distancia=grafo2.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('MallaDijkstra100',distancia)

grafo3=gr.Grafo()
grafo3.GrafoDorogovtsevMendes(100)
grafo3.ArchivoGrafo('grafoDorogovtsevMendes100')
nodo=random.choice(grafo3.ObtenerNodos())
kstra,distancia=grafo3.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('DorogovtsevMendesDijkstra100',distancia)

grafo4=gr.Grafo()
grafo4.GrafoDorogovtsevMendes(500)
grafo4.ArchivoGrafo('grafoDorogovtsevMendes500')
nodo=random.choice(grafo4.ObtenerNodos())
kstra,distancia=grafo4.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('DorogovtsevMendesDijkstra500',distancia)

grafo5=gr.Grafo()
grafo5.GrafoErdosReny(100,150)
grafo5.ArchivoGrafo('grafoErdosReny100')
nodo=random.choice(grafo5.ObtenerNodos())
kstra,distancia=grafo5.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('ErdosRenyDijkstra100',distancia)

grafo6=gr.Grafo()
grafo6.GrafoErdosReny(500,600)
grafo6.ArchivoGrafo('grafoErdosReny500')
nodo=random.choice(grafo6.ObtenerNodos())
kstra,distancia=grafo6.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('ErdosRenyDijkstra500',distancia)

grafo7=gr.Grafo()
grafo7.GrafoGilbert(100,0.1)
grafo7.ArchivoGrafo('grafoGilbert100')
nodo=random.choice(grafo7.ObtenerNodos())
kstra,distancia=grafo7.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('GilbertDijkstra100',distancia)

grafo8=gr.Grafo()
grafo8.GrafoGilbert(500,0.1)
grafo8.ArchivoGrafo('grafoGilbert500')
nodo=random.choice(grafo8.ObtenerNodos())
kstra,distancia=grafo8.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('GilbertDijkstra500',distancia)

grafo9=gr.Grafo()
grafo9.GrafoSimple(100,20)
grafo9.ArchivoGrafo('grafoSimple100')
nodo=random.choice(grafo9.ObtenerNodos())
kstra,distancia=grafo9.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('SimpleDijkstra100',distancia) 
 
grafo10=gr.Grafo()
grafo10.GrafoSimple(500,100)
grafo10.ArchivoGrafo('grafoSimple500')
nodo=random.choice(grafo10.ObtenerNodos())
kstra,distancia=grafo10.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('SimpleDijkstra500',distancia)

grafo11=gr.Grafo()
grafo11.GrafoBarabasiAlbert(100,7)
grafo11.ArchivoGrafo('grafoBarabasiAlbert100')
nodo=random.choice(grafo11.ObtenerNodos())
kstra,distancia=grafo11.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('BarabasiAlbertDijkstra100',distancia)
grafo12=gr.Grafo()
grafo12.GrafoBarabasiAlbert(500,7)
grafo12.ArchivoGrafo('grafoBarabasiAlbert500')
nodo=random.choice(grafo12.ObtenerNodos())
kstra,distancia=grafo12.Dijkstra(inicio=nodo.ObtenerValor())
kstra.ArchivoGrafo('BarabasiAlbertDijkstra500',distancia)                      


print('termino de crear grafos ', time.strftime("%H:%M:%S"))